// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwdbxjhszysjbmvgwcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13ZGJ4amhzenlzamJtdmd3Y3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTY1MDIsImV4cCI6MjA1ODkzMjUwMn0.ZOkrbY3maBuvgvyBRVog3d1xNPBxsT15rXNHsDpM1jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);