
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwdbxjhszysjbmvgwcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13ZGJ4amhzenlzamJtdmd3Y3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTY1MDIsImV4cCI6MjA1ODkzMjUwMn0.ZOkrbY3maBuvgvyBRVog3d1xNPBxsT15rXNHsDpM1jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Extended database type that includes the bot_commands table
export type ExtendedDatabase = Database & {
  public: {
    Tables: {
      bot_commands: {
        Row: {
          id: string;
          command: string;
          description: string;
          response_template: string;
          is_admin_only: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          command: string;
          description: string;
          response_template: string;
          is_admin_only?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          command?: string;
          description?: string;
          response_template?: string;
          is_admin_only?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      } & Database['public']['Tables'];
      communities: {
        Row: {
          id: string;
          name: string;
          description?: string;
          platform: string;
          platform_id: string;
          reach?: number;
          price_per_announcement?: number;
          owner_id: string;
          approval_status?: string;
          created_at: string;
          updated_at?: string;
          region?: string[];
          focus_areas?: string[];
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          platform: string;
          platform_id?: string;
          reach?: number;
          price_per_announcement?: number;
          owner_id: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
          region?: string[];
          focus_areas?: string[];
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          platform?: string;
          platform_id?: string;
          reach?: number;
          price_per_announcement?: number;
          owner_id?: string;
          approval_status?: string;
          created_at?: string;
          updated_at?: string;
          region?: string[];
          focus_areas?: string[];
        };
      };
    };
  } & Database['public'];
};

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
